name: Java CI with Gradle

on:
  push:
    branches: [ neo/1.20 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      env:
        MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN}}
      run: |
        chmod +x ./gradlew
        ./gradlew build --stacktrace --no-daemon
